//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liquid.Feature.MapPlugin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Liquid.Feature.MapPlugin.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiquidMapPluginJavascript.
        /// </summary>
        internal static string ConfigNodeScripts {
            get {
                return ResourceManager.GetString("ConfigNodeScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LiquidMapPluginStylesheets.
        /// </summary>
        internal static string ConfigNodeStyles {
            get {
                return ResourceManager.GetString("ConfigNodeStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scContentControl bing-input.
        /// </summary>
        internal static string scAddressFieldCssClass {
            get {
                return ResourceManager.GetString("scAddressFieldCssClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-location-address.
        /// </summary>
        internal static string scAddressFieldDataAttribute {
            get {
                return ResourceManager.GetString("scAddressFieldDataAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAddressField.
        /// </summary>
        internal static string scAddressSource {
            get {
                return ResourceManager.GetString("scAddressSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Disable Search.
        /// </summary>
        internal static string scFieldDisableSearch {
            get {
                return ResourceManager.GetString("scFieldDisableSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Disable Zooming.
        /// </summary>
        internal static string scFieldDisableZooming {
            get {
                return ResourceManager.GetString("scFieldDisableZooming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin API Key.
        /// </summary>
        internal static string scFieldKey {
            get {
                return ResourceManager.GetString("scFieldKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Pin Label.
        /// </summary>
        internal static string scFieldLabel {
            get {
                return ResourceManager.GetString("scFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Pin Latitude.
        /// </summary>
        internal static string scFieldLatitude {
            get {
                return ResourceManager.GetString("scFieldLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Pin Longitude.
        /// </summary>
        internal static string scFieldLongitude {
            get {
                return ResourceManager.GetString("scFieldLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Pins.
        /// </summary>
        internal static string scFieldPins {
            get {
                return ResourceManager.GetString("scFieldPins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map Plugin Type.
        /// </summary>
        internal static string scFieldType {
            get {
                return ResourceManager.GetString("scFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-location-label.
        /// </summary>
        internal static string scLabelFieldDataAttribute {
            get {
                return ResourceManager.GetString("scLabelFieldDataAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLabelField.
        /// </summary>
        internal static string scLabelSource {
            get {
                return ResourceManager.GetString("scLabelSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-location-latitude.
        /// </summary>
        internal static string scLatitudeFieldDataAttribute {
            get {
                return ResourceManager.GetString("scLatitudeFieldDataAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLatitudeField.
        /// </summary>
        internal static string scLatitudeSource {
            get {
                return ResourceManager.GetString("scLatitudeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data-location-longitude.
        /// </summary>
        internal static string scLongitudeFieldDataAttribute {
            get {
                return ResourceManager.GetString("scLongitudeFieldDataAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLongitudeField.
        /// </summary>
        internal static string scLongitudeSource {
            get {
                return ResourceManager.GetString("scLongitudeSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {676EEA9F-8FD4-4D17-B72C-C020488E289A}.
        /// </summary>
        internal static string scMapSettingsGuid {
            get {
                return ResourceManager.GetString("scMapSettingsGuid", resourceCulture);
            }
        }
    }
}
